  react-app:
    build: .
    container_name: react-app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.react.entrypoints=websecure"
      - "traefik.http.routers.react.tls=true"
      - "traefik.http.routers.react.tls.certresolver=letsencrypt"
      - "traefik.http.services.react.loadbalancer.server.port=80"
    networks:
      - web
